# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: essegi-os
description: Sistema minimale immutabile (Configurazione Privata).
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  # 1 & 2. Installazione e Rimozione Pacchetti (RPM) dal repo privato
  - from-file: private-data/modules/rpm.yml

  # 3. Installazione Flatpak dal repo privato
  - from-file: private-data/modules/flatpak.yml

  # 4. Installazione Cie (Script dal repo privato)
  - type: script
    scripts:
      - ../private-data/modules/install-cie.sh

  # 5. Modulo di firma (Obbligatorio alla fine)
  - type: signing
