# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: essegi-os
description: Sistema minimale immutabile ideale per me.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  # 1. Importazione moduli YAML dal repository privato
  # Percorso relativo alla posizione di questo file (recipe.yml)
  - from-file: private-data/modules/rpm.yml
  - from-file: private-data/modules/flatpak.yml

  # 2. Esecuzione script dal repository privato
  # Il modulo script richiede il percorso dalla radice del repository pubblico
  - type: script
    scripts:
      - ./recipes/private-data/modules/install-cie.sh

  # 3. Modulo di firma (Obbligatorio alla fine)
  - type: signing
