name: bluebuild
on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here
          - recipe.yml
    steps:
      # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: true

      - name: Export string outputs
        id: strings
        run: |
          # Questo serve a passare il nome dell'immagine al generatore di ISO
          echo "image_name=essegi-os" >> $GITHUB_OUTPUT

  # ==== NUOVO JOB DEDICATO PER LA GENERAZIONE DELLA ISO ====
  iso:
    name: Generate ISO
    needs: bluebuild
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate ISO Image
        uses: blue-build/apps-iso-action@v1
        with:
          image_name: ${{ needs.bluebuild.outputs.image_name }}
          installer_version: "44" # Specifica la versione di Fedora (coerente con la tua ricetta)
          # Utilizza i dati appena caricati nel tuo registro GitHub personale
          image_repo: ghcr.io/${{ github.repository_owner }}
          image_tag: latest
